Cliente = input("Digite o nome do cliente:")
Vencimento = input("Digite o dia de vencimento:")
VencimentoMes = input("Digite o mês de vencimento:")
Valor = input("Digite o valor da fatura:")
print("Olá,",Cliente)
print("A sua fatura com vencimento em",Vencimento,"de",VencimentoMes,"no valor de R$",Valor,"está fechada.")